### ISSUE TITLE
关于README.md

### ISSUE THREAD

**Issue by zunsthy** [rccoder/HIT-Mobile-SDK-PHP#1]
把段喵同学的名字放出来真的好吗？

**Comment by rccoder** [comment]
`test.php`嘛, 名字换成其他的也无法验证通过...... @zunsthy

**Comment by zunsthy** [comment]
剛剛手賤去運行了一下，結果發現驗證不通過啊

**Comment by zunsthy** [comment]
L57 `$this->sign = [];` ，直接用有個notice
